{% set name = "OpenSMOG" %}
{% set version = "1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: 847b0836720534e67a08b86ed8f5efba24624d638e7bf30f7a05820e9c715603

build:
  number: 1
  noarch: python
  entry_points:
    - CLINAME=OpenSMOG._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - lxml
    - openmm

test:
  imports:
    - OpenSMOG
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smog-server/OpenSMOG
  summary: OpenSMOG is a Python library for performing molecular dynamics simulations using Structure-Based Models.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://opensmog.readthedocs.io
  dev_url: https://github.com/smog-server/OpenSMOG

extra:
  recipe-maintainers:
    - junioreif
