{% set name = "OpenSMOG" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: 43c91d3184bc8ddde6664e6144d591f748ae403a6ab11481a93955a1202a0d9c

build:
  number: 0
  noarch: python
  entry_points:
    - CLINAME=OpenSMOG._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - openmm
  run:
    - numpy
    - python >={{ python_min }}
    - lxml
    - openmm

test:
  imports:
    - OpenSMOG
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smog-server/OpenSMOG
  summary: OpenSMOG is a Python library for performing molecular dynamics simulations using Structure-Based Models.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://opensmog.readthedocs.io
  dev_url: https://github.com/smog-server/OpenSMOG

extra:
  recipe-maintainers:
    - junioreif
    - smog-server
