{% set name = "OpenSMOG" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 865b88d9c11ce4eb65062bb42f9bb2da97a8eb51d91756b25ad41798c2479098

build:
  number: 0
  noarch: python
  entry_points:
    - CLINAME=OpenSMOG._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - lxml
    - openmm

test:
  imports:
    - OpenSMOG
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smog-server/OpenSMOG
  summary: OpenSMOG is a Python library for performing molecular dynamics simulations using Structure-Based Models.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://opensmog.readthedocs.io
  dev_url: https://github.com/smog-server/OpenSMOG

extra:
  recipe-maintainers:
    - junioreif
